### ISSUE TITLE
`bad data - modules/GodotJS/weaver-editor/jsb_editor_plugin.cpp:214 - [jsb][Warning] failed to write file 'godot.mix.d.ts' to 'res://typings': File not found`

### ISSUE THREAD

**Issue by maikkundev** [ialex32x/GodotJS#3]
I get the warning and error  `bad data - modules/GodotJS/weaver-editor/jsb_editor_plugin.cpp:214 - [jsb][Warning] failed to write file 'godot.mix.d.ts' to 'res://typings': File not found` whenever I try to initialize a TS Project.

Also, trying to generate Godot.d.s prints the error `install and compile ts source at first`

OS: Linux Ubuntu (ZorinOS 17.1)
Godot Branch: 4.2

output:
```
bad data
 modules/GodotJS/weaver-editor/jsb_editor_plugin.cpp:214 - [jsb][Warning] failed to write file 'godot.mix.d.ts' to 'res://typings': File not found
install and compile ts source at first
```

**Comment by ialex32x** [comment]
`godot.mix.d.ts` was added recently which was missed in SCsub. I submitted a new commit fixed this issue.

PS: if the installation report an error about `run_npm_install is not a function`, you can temporarily ignore it and run `npm install` by yourself. I'll investigate it later.
