### ISSUE TITLE
Error `unknown module: res://.godot/GodotJS/Scenes/enemies/basic_enemy.js`

### ISSUE THREAD

**Issue by maikkundev** [ialex32x/GodotJS#7]
- OS: MacOS 14.6.1
- Godot Branch: 4.3
- GodotJS commit: daad15100ee740209f1fb5bc529d4bce95a58874

I get the following error whenever I switch back to the editor or when I run my scenes:

```
 Uncaught Error: unknown module: res://.godot/GodotJS/Scenes/enemies/basic_enemy.js
  Error: unknown module: res://.godot/GodotJS/Scenes/enemies/basic_enemy.js (User)
  modules/GodotJS/weaver/jsb_gdjs_script.cpp:435 - [jsb][Error] the javascript file is missing: res://.godot/GodotJS/Scenes/enemies/basic_enemy.js (source: res://Scenes/enemies/basic_enemy.ts), please ensure that all typescript source files have already been compiled using the typescript compiler ('tsc'). (User)
```

the issue seems to be that `tsc` compiles the `.ts` files on the root of `.godot/GodotJS`, but the editor expects for files on `.godot/GodotJS/<relative_path_of_ts_file>/`

**Comment by ialex32x** [comment]
This issue should be caused by missing config of `rootDir` in `tsconfig.json`. Try uncomment the line:
`// "rootDir": "./",`
to ` "rootDir": "./",`.

I'll update the default `tsconfig.json` in next commit if this works.

**Comment by maikkundev** [comment]
Yes, that fixed it :D 
I have been experiencing other issues tho, will create new Issues!
